version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  build:
    commands:
      - echo Packaging templates...
      - aws s3 cp s3-backup.yaml s3://iac-bucket-azamcloud/
      - aws s3 cp opensearch.yaml s3://iac-bucket-azamcloud/
      - aws s3 cp firehose.yaml s3://iac-bucket-azamcloud/
      - aws s3 cp cwtofire.yaml s3://iac-bucket-azamcloud/ 
      - aws cloudformation deploy --template-file masterstack.yaml --stack-name Opensearch-stacks-dev --capabilities CAPABILITY_NAMED_IAM --parameter-overrides file://prod-params.json

artifacts:
  files:
    - '**/*'
