AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DomainName:
    Type: String

  EngineVersion:
    Type: String

  InstanceType:
    Type: String

  InstanceCount:
    Type: Number

  Environment:
    Type: String

  FirehoseRoleArn:
    Type: String

Resources:
  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: !Ref DomainName
      EngineVersion: !Ref EngineVersion
      ClusterConfig:
        InstanceType: !Ref InstanceType
        InstanceCount: !Ref InstanceCount
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 20
      NodeToNodeEncryptionOptions:
        Enabled: true
      EncryptionAtRestOptions:
        Enabled: true
      DomainEndpointOptions:
        EnforceHTTPS: true
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref FirehoseRoleArn
            Action: 'es:*'
            Resource: !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${DomainName}/*"

      Tags:
        - Key: Name
          Value: !Sub "${DomainName}-${Environment}"

Outputs:
  OpenSearchDomainEndpoint:
    Value: !GetAtt OpenSearchDomain.DomainEndpoint

  OpenSearchDomainArn:
    Value: !GetAtt OpenSearchDomain.Arn

