AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:
    Type: String

  BucketName:
    Type: String
    

Resources:
  BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: !Sub "${BucketName}-${Environment}"

Outputs:
  BackupBucketName:
    Value: !Ref BackupBucket

  BackupBucketArn:
    Value: !GetAtt BackupBucket.Arn
